name: book-check-text

# Only run this when the master branch changes 
on:
  workflow_dispatch:
  pull_request:

# This job installs dependencies, build the book, and pushes it to `gh-pages`
jobs:
  checkText:
    name: Spell check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Spell check
        # problem matching breaks loop when it finds unrelated data, so we use reverse grep to clear output
        run: |
          echo "::add-matcher::.github/problem-matchers/yaspeller.json"
          set -o pipefail; npx yaspeller -c .yaspellerrc.json . 2>&1 >/dev/null | grep -v "\-\-\-\-\-" | grep -v "Typos"
          echo "::remove-matcher owner=yaspeller::"