name: deploy-branch

on:
  pull_request:

jobs:
  deploy_branch_aws:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: checkout code
        uses: actions/checkout@v2

      # Another magic action
      - name: get branch name
        uses: nelonoel/branch-name@v1.0.1

      # Set up PY38
      - name: Set up Python 3.8
        uses: actions/setup-python@v2.2.2
        with:
          python-version: 3.8

      # Set up POETRY
      - name: Set up poetry
        uses: snok/install-poetry@v1.1.6
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true

      # Install dependencies
      - name: Install dependencies
        run: |
          poetry install

      # todo: replace with a more sane solution
      - name: install tensorflow_quantum
        run: |
          poetry run pip install --upgrade pip
          poetry run pip install -U tensorflow==2.5.1
          poetry run pip install -U tensorflow_quantum
          poetry run pip install -U tfq-nightly

      - name: export some env & token
        env:
          DWAVE_TOKEN: ${{ secrets.DWAVE_TOKEN }}
          CURRENT_BRANCH: ${ BRANCH_NAME }
          AWS_SSH_KEY: ${{ secrets.AWS_SSH_KEY }}
          SSH_KEY_PATH: /home/runner/.ssh/key.pem
          AWS_HOST: 54.89.156.216
          AWS_USER: ubuntu
        run: |
          echo "branch: $CURRENT_BRANCH"

      - name: add SSH key-file
        run: |
          mkdir -p /home/runner/.ssh
          echo AWS_SSH_KEY > $SSH_KEY_PATH
          chmod 600 $SSH_KEY_PATH

      - name: build the book
        run: |
          poetry run jupyter-book build ./qmlcourseRU

      - name: deploy
        run: |
          poetry run python ./tools/deploy2aws.py ./

#          export AWS_HOST="54.89.156.216"
#          export AWS_USER="ubuntu"
#          export SSH_KEY="/home/runner/.ssh/key.pem"
#          export CURRENT_BRANCH="${BRANCH_NAME}"
