name: test-psi4-setup

# Only run this when the master branch changes
on:
  workflow_dispatch:

# This job installs dependencies, build the book, and pushes it to `gh-pages`
jobs:
  build:
    runs-on: macOS-latest
    name: Test psi4 setup
    steps:
      - uses: actions/checkout@v2
      - name: Setup conda
        uses: s-weigand/setup-conda@v1
        with:
          update-conda: true
          python-version: 3.8
          conda-channels: anaconda, conda-forge
      - run: conda --version
      - run: which python
      - run: conda install psi4=1.4rc3 python=3.8 -c psi4/label/dev -y
      - run: psi4 --test